/**
 * Starlight Theme Plugin: starlight-theme-stellar-cyan
 * Generated by @knowledge-forge-ai/theme-forge-stellar-loom
 */

export default function themePlugin(options = {}) {
  return {
    name: "starlight-theme-stellar-cyan",
    hooks: {
      "config:setup"({ config, updateConfig, logger }) {
        const existingCustomCss = Array.isArray(config.customCss) ? config.customCss : [];
        const themeCssPath = "starlight-theme-stellar-cyan/styles/theme.css";

        // Cascade order: theme stylesheet defaults first, consumer custom CSS second
        const customCss = existingCustomCss.includes(themeCssPath)
          ? [...existingCustomCss]
          : [themeCssPath, ...existingCustomCss];

        const existingComponents = config.components ? { ...config.components } : {};
        updateConfig({
          customCss,
        });
      },
    },
  };
}
