import { compileTheme, computeSha256, COMPILER_PACKAGE, COMPILER_VERSION } from "../compiler/index.js";
import { validateThemeSpecification } from "../schema/validator.js";
import { validatePackageMetadata } from "./metadata.js";
import { emitPageTitleFrameComponent } from "./templates/page-title-frame.js";
import { AGPL_3_LICENSE_TEXT, FIRST_PARTY_NOTICE_TEXT, COMMERCIAL_LICENSE_TEXT } from "./legal.js";
import type {
  ApprovedTemplateId,
  GeneratePackageOptions,
  GeneratePackageResult,
  PackageFileRecord,
  PackageProvenance,
  PackageProvenanceCategory,
} from "./types.js";

function getFileCategory(relativePath: string): PackageProvenanceCategory {
  if (relativePath === "package.json" || relativePath === "theme.descriptor.json" || relativePath === "provenance.json") {
    return "generated-metadata";
  }
  if (relativePath === "theme.json") {
    return "user-authored-data";
  }
  if (relativePath.startsWith("styles/")) {
    return "generated-syntax";
  }
  if (relativePath === "LICENSE" || relativePath === "NOTICE" || relativePath === "COMMERCIAL-LICENSE.md") {
    return "legal-notice";
  }
  return "first-party-expression";
}

export function generateThemePackage(options: GeneratePackageOptions): GeneratePackageResult {
  // 1. Validate package metadata
  const metadata = validatePackageMetadata(options.metadata);

  // Apply template override if specified in options
  if (options.template !== undefined) {
    if (options.template.trim().length > 0) {
      const tmpl = options.template.trim() as ApprovedTemplateId;
      if (tmpl !== "page-title-frame") {
        throw new Error(`Unknown or unapproved template ID: '${options.template}'`);
      }
      metadata.template = tmpl;
    }
  }

  // 2. Validate theme specification and compile CSS
  const validatedSpec = validateThemeSpecification(options.themeSpec);
  const compileOptions: { cssFile: string; strictContrast?: boolean } = {
    cssFile: "styles/theme.css",
  };
  if (options.strictContrast !== undefined) {
    compileOptions.strictContrast = options.strictContrast;
  }
  const compilation = compileTheme(validatedSpec, compileOptions);

  const hasTemplate = metadata.template !== undefined;
  const canonicalThemeJson = JSON.stringify(compilation.specification, null, 2) + "\n";
  const descriptorJson = JSON.stringify(compilation.descriptor, null, 2) + "\n";

  // 3. Construct package.json
  const packageExports: Record<string, unknown> = {
    ".": {
      types: "./index.d.ts",
      import: "./index.js",
    },
    "./styles/*": "./styles/*",
  };
  if (hasTemplate) {
    packageExports["./components/*"] = "./components/*";
  }

  const packageFiles: string[] = [
    "index.js",
    "index.d.ts",
    "styles",
    "theme.descriptor.json",
    "theme.json",
    "provenance.json",
    "README.md",
    "LICENSE",
    "NOTICE",
    "COMMERCIAL-LICENSE.md",
  ];
  if (hasTemplate) {
    packageFiles.push("components");
  }

  const packageJsonObj: Record<string, unknown> = {
    name: metadata.name,
    version: metadata.version,
    description: metadata.description ?? `${compilation.specification.name} Starlight theme plugin`,
    private: true,
    type: "module",
    license: metadata.license ?? "AGPL-3.0-or-later",
    exports: packageExports,
    files: packageFiles,
    peerDependencies: {
      "@astrojs/starlight": "^0.42.0",
      astro: "^7.3.1",
    },
    engines: {
      node: ">=22",
    },
  };
  if (metadata.author) {
    packageJsonObj.author = metadata.author;
  }
  const packageJsonContent = JSON.stringify(packageJsonObj, null, 2) + "\n";

  // 4. Construct index.js (runtime Starlight plugin)
  const templateInjectionCode =
    hasTemplate && metadata.template === "page-title-frame"
      ? `
        if (existingComponents.PageTitle) {
          logger?.info?.(\`[${metadata.name}] Preserving existing consumer PageTitle component override\`);
        } else {
          existingComponents.PageTitle = ${JSON.stringify(`${metadata.name}/components/PageTitleFrame.astro`)};
        }
        updateConfig({
          customCss,
          components: existingComponents,
        });`
      : `
        updateConfig({
          customCss,
        });`;

  const indexJsContent = `/**
 * Starlight Theme Plugin: ${metadata.name}
 * Generated by @knowledge-forge-ai/theme-forge-stellar-loom
 */

export default function themePlugin(options = {}) {
  return {
    name: ${JSON.stringify(metadata.name)},
    hooks: {
      "config:setup"({ config, updateConfig, logger }) {
        const existingCustomCss = Array.isArray(config.customCss) ? config.customCss : [];
        const themeCssPath = ${JSON.stringify(`${metadata.name}/styles/theme.css`)};

        // Cascade order: theme stylesheet defaults first, consumer custom CSS second
        const customCss = existingCustomCss.includes(themeCssPath)
          ? [...existingCustomCss]
          : [themeCssPath, ...existingCustomCss];

        const existingComponents = config.components ? { ...config.components } : {};${templateInjectionCode}
      },
    },
  };
}
`;

  // 5. Construct index.d.ts
  const indexDtsContent = `export interface StarlightPluginHooks {
  "config:setup": (context: {
    config: Record<string, unknown>;
    updateConfig: (newConfig: Record<string, unknown>) => void;
    logger?: {
      info: (message: string) => void;
      warn: (message: string) => void;
      error: (message: string) => void;
    };
  }) => void | Promise<void>;
}

export interface StarlightThemePlugin {
  name: string;
  hooks: StarlightPluginHooks;
}

export default function themePlugin(options?: Record<string, unknown>): StarlightThemePlugin;
`;

  // 6. Construct README.md
  const templateReadmeSection =
    hasTemplate && metadata.template === "page-title-frame"
      ? `
## Component Overrides

This package provides an opt-in \`page-title-frame\` component override wrapping Starlight's \`PageTitle.astro\`.
If your Starlight configuration already specifies a \`components.PageTitle\` override, your override is preserved and takes precedence.
`
      : "";

  const readmeContent = `# ${metadata.name}

${metadata.description ?? `${compilation.specification.name} Starlight theme plugin`}

Generated by \`@knowledge-forge-ai/theme-forge-stellar-loom\` (${COMPILER_VERSION}).

## Compatibility

- **Astro**: \`^7.3.1\`
- **Starlight**: \`^0.42.0\`
- **Node.js**: \`>=22\`

## Installation

This package is a private unregistered candidate (\`"private": true\`) not published to the npm registry.

To install this package into a Starlight documentation project, create a repeatable local tarball using local npm pack:

\`\`\`bash
npm pack
\`\`\`

Then install the tarball into your consumer project with installation scripts disabled:

\`\`\`bash
npm install --ignore-scripts /path/to/tarball
\`\`\`

## Configuration

Add the theme plugin to your \`astro.config.mjs\`:

\`\`\`javascript
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import themePlugin from "${metadata.name}";

export default defineConfig({
  integrations: [
    starlight({
      title: "Documentation",
      plugins: [themePlugin()],
    }),
  ],
});
\`\`\`

## Cascade Order & Custom CSS

The plugin automatically registers its theme stylesheet before any user-defined custom CSS:
\`[${metadata.name}/styles/theme.css, ...customCss]\`

This cascade order ensures consumer custom CSS loads after the theme stylesheet:
- Dark/base theme tokens defined at \`:root\` or \`:root, ::backdrop\` (specificity \`0,1,0\`) are overridden by consumer \`:root\` rules.
- Light mode tokens emitted at \`:root[data-theme='light']\` (specificity \`0,2,0\`) are overridden by consumer rules matching that specificity (e.g. \`:root[data-theme='light']\`).
- Component and utility class selectors in consumer custom CSS take precedence over theme defaults when specificity is equal or higher.
${templateReadmeSection}
## Licensing

Dual-licensed under the GNU Affero General Public License v3.0 or later (AGPL-3.0-or-later) and commercial license terms. See \`LICENSE\`, \`NOTICE\`, and \`COMMERCIAL-LICENSE.md\`.
`;

  // Raw file map (excluding provenance.json for initial pass)
  const preliminaryFiles: Record<string, string> = {
    "package.json": packageJsonContent,
    "index.js": indexJsContent,
    "index.d.ts": indexDtsContent,
    "styles/theme.css": compilation.css,
    "theme.descriptor.json": descriptorJson,
    "theme.json": canonicalThemeJson,
    "README.md": readmeContent,
    "LICENSE": AGPL_3_LICENSE_TEXT,
    "NOTICE": FIRST_PARTY_NOTICE_TEXT,
    "COMMERCIAL-LICENSE.md": COMMERCIAL_LICENSE_TEXT,
  };

  if (hasTemplate && metadata.template === "page-title-frame") {
    preliminaryFiles["components/PageTitleFrame.astro"] = emitPageTitleFrameComponent();
  }

  // 7. Generate provenance records for all emitted files
  const sortedFilePaths = Object.keys(preliminaryFiles).sort();
  const filesRecord: PackageFileRecord[] = sortedFilePaths.map((relPath) => {
    const content = preliminaryFiles[relPath]!;
    const bytes = Buffer.from(content, "utf8");
    return {
      path: relPath,
      size: bytes.byteLength,
      sha256: computeSha256(content),
      category: getFileCategory(relPath),
    };
  });

  const provenance: PackageProvenance = {
    schema: "tfsl.package-provenance-v1",
    schemaVersion: 1,
    packageName: metadata.name,
    packageVersion: metadata.version,
    generator: COMPILER_PACKAGE,
    generatorVersion: COMPILER_VERSION,
    themeName: compilation.specification.name,
    themeVersion: compilation.specification.version,
    themeInputDigest: compilation.inputDigest,
    cssOutputDigest: compilation.outputDigest,
    files: filesRecord,
    licensingNotice: "Licensed under AGPL-3.0-or-later. Commercial dual licensing available directly from The Knowledge Forge Authors.",
  };
  if (hasTemplate && metadata.template !== undefined) {
    provenance.template = metadata.template;
  }

  const provenanceJson = JSON.stringify(provenance, null, 2) + "\n";
  preliminaryFiles["provenance.json"] = provenanceJson;

  // Final sorted files map
  const finalMap = new Map<string, string>();
  for (const relPath of Object.keys(preliminaryFiles).sort()) {
    finalMap.set(relPath, preliminaryFiles[relPath]!);
  }

  return {
    metadata,
    themeSpec: compilation.specification,
    themeCanonicalJson: canonicalThemeJson,
    themeInputDigest: compilation.inputDigest,
    cssContent: compilation.css,
    cssOutputDigest: compilation.outputDigest,
    descriptor: compilation.descriptor,
    provenance,
    files: finalMap,
    diagnostics: compilation.diagnostics,
  };
}
