/**
 * Starlight Theme Plugin: starlight-theme-amber-forge
 * Generated by @knowledge-forge-ai/theme-forge-stellar-loom
 */

export default function themePlugin(options = {}) {
  return {
    name: "starlight-theme-amber-forge",
    hooks: {
      "config:setup"({ config, updateConfig, logger }) {
        const existingCustomCss = Array.isArray(config.customCss) ? config.customCss : [];
        const themeCssPath = "starlight-theme-amber-forge/styles/theme.css";

        // Cascade order: theme stylesheet defaults first, consumer custom CSS second
        const customCss = existingCustomCss.includes(themeCssPath)
          ? [...existingCustomCss]
          : [themeCssPath, ...existingCustomCss];

        const existingComponents = config.components ? { ...config.components } : {};
        if (existingComponents.PageTitle) {
          logger?.info?.(`[starlight-theme-amber-forge] Preserving existing consumer PageTitle component override`);
        } else {
          existingComponents.PageTitle = "starlight-theme-amber-forge/components/PageTitleFrame.astro";
        }
        updateConfig({
          customCss,
          components: existingComponents,
        });
      },
    },
  };
}
